mtgtrends/urls.py
from django.urls import path
from . import views

app_name = 'mtgtrends'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:item_id>/', views.detail, name='detail'),
]

mtgtrendsproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mtgtrends.urls')),
]

mtgtrends/models.py
from django.db import models

# Create your models here.

mtgtrends/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.template.response import TemplateResponse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
import requests, json, pandas as pd, io, matplotlib, matplotlib.pyplot as plt, base64
matplotlib.use('Agg')

def index(request):
    params = request.GET.copy()

    # 語句検索
    search_word = request.GET.get('name')
    if search_word:
        res = requests.get('https://upauper63-mtgtrendsapi.herokuapp.com/api/items/?search=' + search_word)
    else:
        res = requests.get('https://upauper63-mtgtrendsapi.herokuapp.com/api/items/')
        search_word = ''

    items = json.loads(res.text)

    # ページネータ処理
    if 'page' in params:
        page = params['page']
        del params['page']
    else:
        page = 1
    search_params = params.urlencode()
    paginator = Paginator(items, 50)
    try:
        items = paginator.page(page)
    except (EmptyPage, PageNotAnInteger):
        items = paginator.page(1)

    return TemplateResponse(request, 'mtgtrends/index.html', {'items': items, 'search_params': search_params, 'search_word': search_word})


def detail(request, item_id):
    res = requests.get('https://upauper63-mtgtrendsapi.herokuapp.com/api/item/?id=' + str(item_id))
    item = json.loads(res.text)
    df = pd.DataFrame(item[0]['trends'], columns=['Date', 'Price'])
    df.plot(x="Date", y="Price", ylabel='Price', rot=30, marker="o", legend=None)
    buf = io.BytesIO()
    plt.savefig(buf, format='png', bbox_inches='tight')
    svg = buf.getvalue()
    graph = base64.b64encode(svg).decode('utf-8')
    buf.close()
    plt.cla()
    return TemplateResponse(request, 'mtgtrends/detail.html', {'graph': graph, 'name': item[0]['name']})

mtgtrends/templates/mtgtrends/base.html
<!doctype html>
{% load static %}
<html lang="ja">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
        integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="icon" type="image/png" href="{% static 'icon/favicon.png' %}">
    <!-- CustomCss -->
    <link href="{% static 'css/styles.css' %}" rel="stylesheet">
    <title>MTGTrends | {% block title %}{% endblock %}</title>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-3">
        <a class="navbar-brand" href="{% url 'mtgtrends:index' %}">MTGTrends</a>
    </nav>
    <div class="container">
        {% block content %}{% endblock %}
    </div>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
        integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI"
        crossorigin="anonymous"></script>
</body>
</html>

mtgtrends/templates/mtgtrends/detail.html
<!DOCTYPE html>
{% extends 'mtgtrends/base.html' %}
{% block title %}Detail{% endblock %}
{% block content %}
<div class="text-center"><img class="graph" src="data:image/png;base64,{{ graph | safe }}"></div>
<p class="text-center detail-item-name">{{ name }}</p>
<a class="btn btn-primary float-right" href="{{request.META.HTTP_REFERER}}" role="button">Back</a>
{% endblock %}

mtgtrends/templates/mtgtrends/index.html
<!DOCTYPE html>
{% extends 'mtgtrends/base.html' %}
{% block title %}List{% endblock %}
{% block content %}
<form class="form-inline" method="GET">
    <div class="form-group mb-2 col-10">
      <label for="name" class="mr-2">CardName</label>
      <input type="text" class="form-control col-10" id="name" name="name" value="{{ search_word }}">
    </div>
    <button type="submit" class="btn btn-primary mb-2">Search</button>
</form>

{% if items.has_previous %}
<a href="?page={{ items.previous_page_number }}&{{ search_params }}">&lt;</a>
{% else %}
<span>&lt;</span>
{% endif %}
{{ items.number }} / {{ items.paginator.num_pages }}
{% if items.has_next %}
<a href="?page={{ items.next_page_number}}&{{ search_params }} ">&gt;</a>
{% else %}
<span>&gt;</span>
{% endif %}

<table class="table">
    <thead>
        <tr>
            <th scope="col" style="width:65%">CardName</th>
            <th scope="col" style="width:15%">Diff</th>
            <th scope="col" style="width:20%"></th>
        </tr>
    </thead>
    <tbody>
        {% for item in items %}
        <tr>
            <td>{{ item.name }}</td>
            {% if item.diff_price_prev is None %}
            <td>NO DATA</td>
            {% else %}
            <td>{{ item.diff_price_prev }}</td>
            {% endif %}
            <td><a href="{% url 'mtgtrends:detail' item_id=item.id %}" class="btn btn-outline-primary btn-sm" role="button">Detail</a></td>
        </tr>
        {% endfor %}
    </tbody>
</table>
<p class="text-right small">＊￥300～￥100,000の価格帯のカードが集計対象です。</p>
{% endblock %}